/* ========================================
   TRAVEL TRIPPY - Curated Data Layer
   50+ Hidden Gems, Foods, Chat Patterns
   ======================================== */

window.TT = window.TT || {};

// ========================================
// CATEGORIES
// ========================================
TT.categories = [
  { id: 'mountains', label: 'Mountains', icon: '🏔️' },
  { id: 'waterfalls', label: 'Waterfalls', icon: '💧' },
  { id: 'lakes', label: 'Lakes', icon: '🏞️' },
  { id: 'beaches', label: 'Beaches', icon: '🏖️' },
  { id: 'forests', label: 'Forests', icon: '🌲' },
  { id: 'villages', label: 'Villages', icon: '🏘️' },
  { id: 'forts', label: 'Forts & Ruins', icon: '🏰' },
  { id: 'temples', label: 'Temples', icon: '🛕' },
  { id: 'adventure', label: 'Adventure', icon: '🧗' },
  { id: 'photography', label: 'Photography', icon: '📸' },
  { id: 'wildlife', label: 'Wildlife', icon: '🦁' },
  { id: 'heritage', label: 'Heritage', icon: '🏛️' },
];

// ========================================
// DESTINATIONS – 50+ Hidden Gems of India
// ========================================
TT.destinations = [
  {
    id: 'spiti-valley',
    name: 'Spiti Valley',
    state: 'Himachal Pradesh',
    region: 'North India',
    tagline: 'The Middle Land Between Tibet and India',
    description: 'Spiti Valley is a cold desert mountain valley located high in the Himalayas. With its dramatic landscapes of barren mountains, ancient monasteries perched on cliffs, and crystal-clear skies perfect for stargazing, Spiti feels like stepping onto another planet. The valley remains cut off from the rest of the world for nearly six months due to heavy snowfall, preserving its pristine beauty and ancient Buddhist culture.',
    localInsight: 'Visit Key Monastery at sunrise for the most ethereal experience. The monks begin their morning prayers as golden light floods the valley. Also, try the local Chhang (barley beer) at a homestay — it warms you up instantly in the cold!',
    coordinates: { lat: 32.2462, lng: 78.0189 },
    categories: ['mountains', 'adventure', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'June – September',
    budget: { min: 8000, max: 15000, per: '3 days' },
    nearestCity: { name: 'Manali', distance: 200, travelTime: '10 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Thukpa', 'Momos', 'Chhang', 'Butter Tea'],
    activities: ['Trekking', 'Stargazing', 'Monastery Visits', 'Photography'],
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #2563EB 50%, #7DD3FC 100%)',
    emoji: '🏔️'
  },
  {
    id: 'mawlynnong',
    name: 'Mawlynnong',
    state: 'Meghalaya',
    region: 'North-East India',
    tagline: "Asia's Cleanest Village",
    description: "Known as 'God's Own Garden', Mawlynnong earned the title of Asia's cleanest village. This tiny Khasi settlement is a living example of community-driven cleanliness and sustainable living. Bamboo dustbins line the pathways, gardens bloom with orchids, and the living root bridges nearby showcase nature's engineering marvels.",
    localInsight: "Don't miss the Sky Walk — a bamboo platform built on a giant tree that gives a panoramic view of the Bangladesh plains. The village women run most businesses here; support the local homestays run by Khasi families.",
    coordinates: { lat: 25.2008, lng: 91.9190 },
    categories: ['villages', 'photography', 'forests'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 3000, max: 6000, per: '2 days' },
    nearestCity: { name: 'Shillong', distance: 78, travelTime: '3 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Jadoh', 'Doh Khlieh', 'Tungrymbai', 'Ki Kpu'],
    activities: ['Village Walk', 'Root Bridge Trek', 'Sky Walk', 'Photography'],
    gradient: 'linear-gradient(135deg, #065F46 0%, #10B981 50%, #6EE7B7 100%)',
    emoji: '🌿'
  },
  {
    id: 'gandikota',
    name: 'Gandikota',
    state: 'Andhra Pradesh',
    region: 'South India',
    tagline: 'The Grand Canyon of India',
    description: 'Hidden away in the Kurnool district, Gandikota features a stunning gorge formed by the Pennar River cutting through Erramala hills. The ancient Gandikota Fort sits dramatically on the edge of this canyon, offering jaw-dropping views. Despite its grandeur rivaling the Grand Canyon, this place sees barely a fraction of tourists.',
    localInsight: 'Camp overnight at the gorge edge to witness both sunset and sunrise over the canyon — the colors are unreal. The fort has a beautiful mosque and temple side by side, reflecting the harmony of this region.',
    coordinates: { lat: 15.2491, lng: 78.2855 },
    categories: ['forts', 'adventure', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'October – February',
    budget: { min: 2500, max: 5000, per: '2 days' },
    nearestCity: { name: 'Kurnool', distance: 80, travelTime: '2 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Rayalaseema Biryani', 'Uggani', 'Pesarattu'],
    activities: ['Canyon Viewing', 'Camping', 'Fort Exploration', 'Kayaking'],
    gradient: 'linear-gradient(135deg, #92400E 0%, #D97706 50%, #FCD34D 100%)',
    emoji: '🏜️'
  },
  {
    id: 'chopta',
    name: 'Chopta',
    state: 'Uttarakhand',
    region: 'North India',
    tagline: 'Mini Switzerland of India',
    description: 'Chopta is a small hamlet nestled in the Garhwal Himalayas, surrounded by dense forests of pine, deodar, and rhododendron. It serves as the base for the Tungnath–Chandrashila trek, which leads to the world\'s highest Shiva temple. In winter, the entire landscape transforms into a snow-white wonderland.',
    localInsight: 'Start the Chandrashila trek before dawn to catch sunrise from the summit — you can see Nanda Devi, Trishul, and Chaukhamba peaks glowing golden. The Maggi and chai at the small shacks along the trail are legendary!',
    coordinates: { lat: 30.4329, lng: 79.2099 },
    categories: ['mountains', 'adventure', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'March – June, Sep – Nov',
    budget: { min: 3000, max: 7000, per: '2 days' },
    nearestCity: { name: 'Rishikesh', distance: 210, travelTime: '8 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Pahadi Dal', 'Mandua Roti', 'Kafuli', 'Bal Mithai'],
    activities: ['Tungnath Trek', 'Chandrashila Summit', 'Bird Watching', 'Camping'],
    gradient: 'linear-gradient(135deg, #1E40AF 0%, #3B82F6 50%, #93C5FD 100%)',
    emoji: '⛰️'
  },
  {
    id: 'gokarna',
    name: 'Gokarna',
    state: 'Karnataka',
    region: 'South India',
    tagline: 'The Quieter, More Beautiful Goa',
    description: 'Once a sleepy temple town, Gokarna has emerged as the perfect alternative to crowded Goa. Its crescent-shaped beaches — Om Beach, Half Moon Beach, and Paradise Beach — are accessible only by trekking through coastal trails. The blend of pristine beaches, temple heritage, and bohemian backpacker culture makes it uniquely charming.',
    localInsight: 'Trek from Om Beach to Paradise Beach during late afternoon — you\'ll pass through Half Moon Beach. Carry water and snacks. Stay in the beach shacks at Kudle Beach for the most authentic experience.',
    coordinates: { lat: 14.5479, lng: 74.3188 },
    categories: ['beaches', 'adventure', 'temples'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 3000, max: 8000, per: '3 days' },
    nearestCity: { name: 'Hubli', distance: 140, travelTime: '4 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Fish Curry Rice', 'Jolada Rotti', 'Kundapura Chicken', 'Neer Dosa'],
    activities: ['Beach Trekking', 'Temple Visit', 'Surfing', 'Beach Camping'],
    gradient: 'linear-gradient(135deg, #0E7490 0%, #06B6D4 50%, #67E8F9 100%)',
    emoji: '🏖️'
  },
  {
    id: 'majuli',
    name: 'Majuli Island',
    state: 'Assam',
    region: 'North-East India',
    tagline: 'World\'s Largest River Island',
    description: 'Majuli is the world\'s largest river island, formed by the mighty Brahmaputra. This cultural capital of Assamese civilization is home to neo-Vaishnavite Satras (monasteries) where monks preserve ancient art forms including mask-making, classical dance, and manuscript painting. The island\'s ecosystem of wetlands and migratory birds makes it a nature lover\'s paradise.',
    localInsight: 'Visit Kamalabari Satra to watch the monks create their stunning masks from bamboo and clay. Time your visit with the Raas Festival (November) for an unforgettable cultural immersion.',
    coordinates: { lat: 26.9500, lng: 94.1667 },
    categories: ['heritage', 'photography', 'wildlife'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 3000, max: 6000, per: '3 days' },
    nearestCity: { name: 'Jorhat', distance: 20, travelTime: '1.5 hrs (ferry)' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Assamese Thali', 'Pitika', 'Masor Tenga', 'Pitha'],
    activities: ['Satra Visits', 'Mask Making', 'Bird Watching', 'Cycling'],
    gradient: 'linear-gradient(135deg, #064E3B 0%, #059669 50%, #6EE7B7 100%)',
    emoji: '🏝️'
  },
  {
    id: 'ziro-valley',
    name: 'Ziro Valley',
    state: 'Arunachal Pradesh',
    region: 'North-East India',
    tagline: 'UNESCO Heritage Rice Paddy Paradise',
    description: 'Ziro Valley is a stunning flatland nestled among pine-clad hills in lower Subansiri district. Home to the Apatani tribe — known for unique facial tattoos and sustainable rice-fish farming — this UNESCO World Heritage tentative site offers a glimpse into one of India\'s most fascinating indigenous cultures.',
    localInsight: 'Visit during the Ziro Music Festival (September) for an incredible mix of indie music and tribal culture. Ask Apatani elders about their rice-fish cultivation — it\'s a 3000-year-old sustainable practice!',
    coordinates: { lat: 27.5884, lng: 93.8311 },
    categories: ['villages', 'heritage', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'March – October',
    budget: { min: 5000, max: 10000, per: '3 days' },
    nearestCity: { name: 'Itanagar', distance: 115, travelTime: '5 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Apatani Thali', 'Bamboo Shoot Curry', 'Rice Beer', 'Smoked Meat'],
    activities: ['Tribal Village Walk', 'Paddy Field Walks', 'Hiking', 'Music Festival'],
    gradient: 'linear-gradient(135deg, #14532D 0%, #22C55E 50%, #86EFAC 100%)',
    emoji: '🌾'
  },
  {
    id: 'chitkul',
    name: 'Chitkul',
    state: 'Himachal Pradesh',
    region: 'North India',
    tagline: 'Last Inhabited Village on Indo-Tibet Border',
    description: 'Chitkul is the last village on the old Hindustan-Tibet trade route. Sitting at 11,320 feet with the Baspa River flowing beside it, this hamlet feels like the edge of the world. Traditional Kinnauri wooden houses with slate roofs, apple orchards, and the imposing Himalayan peaks create a picture-perfect setting.',
    localInsight: 'Walk to the ITBP checkpost — it\'s the last point before the Tibet border. The village temple has exquisite wood carvings. Try rajma chawal at any local dhaba here; the slow-cooked high-altitude rajma has a unique flavor.',
    coordinates: { lat: 31.3506, lng: 78.4367 },
    categories: ['mountains', 'villages', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'May – October',
    budget: { min: 4000, max: 8000, per: '2 days' },
    nearestCity: { name: 'Shimla', distance: 240, travelTime: '10 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Siddu', 'Chha Gosht', 'Rajma Chawal', 'Aktori'],
    activities: ['Village Walk', 'River Trail', 'Photography', 'Apple Orchard Visit'],
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #3B82F6 50%, #BFDBFE 100%)',
    emoji: '🏘️'
  },
  {
    id: 'hampi',
    name: 'Hampi',
    state: 'Karnataka',
    region: 'South India',
    tagline: 'Ruins of the Vijayanagara Empire',
    description: 'Hampi is an awe-inspiring open-air museum of the Vijayanagara Empire. Massive boulder-strewn landscapes cradle ancient temples, royal complexes, and bazaars. The surreal terrain of golden boulders balanced against each other, combined with the Tungabhadra River, creates an otherworldly atmosphere that photographers and history lovers adore.',
    localInsight: 'Cross the river by coracle to the hippie side of Hampi for sunset views and laid-back cafes. Rent a bicycle to explore — most ruins are spread over 26 sq km. Visit Virupaksha Temple at dawn when it\'s peaceful.',
    coordinates: { lat: 15.3350, lng: 76.4600 },
    categories: ['heritage', 'photography', 'temples'],
    difficulty: 'Easy',
    bestSeason: 'October – February',
    budget: { min: 3000, max: 6000, per: '3 days' },
    nearestCity: { name: 'Hospet', distance: 13, travelTime: '30 min' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Obbattu', 'Jolada Rotti', 'Bisi Bele Bath', 'Mango Lassi'],
    activities: ['Temple Exploration', 'Coracle Ride', 'Cycling', 'Rock Climbing'],
    gradient: 'linear-gradient(135deg, #78350F 0%, #B45309 50%, #FDE68A 100%)',
    emoji: '🏛️'
  },
  {
    id: 'dzukou-valley',
    name: 'Dzukou Valley',
    state: 'Nagaland',
    region: 'North-East India',
    tagline: 'Valley of Flowers of the East',
    description: 'Hidden between Nagaland and Manipur, Dzukou Valley transforms into a carpet of wildflowers during monsoon — lilies, aconitums, euphorbias, and many species found nowhere else on earth. The misty valley at 8,000 feet with bamboo groves and crystal streams offers one of the most beautiful treks in India.',
    localInsight: 'The trek starts from Viswema village. Carry a sleeping bag and tent as the overnight camping inside the valley is magical. The Angami Naga guides are incredibly warm — share a meal with them for stories about the valley.',
    coordinates: { lat: 25.5367, lng: 93.9117 },
    categories: ['mountains', 'adventure', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'June – September',
    budget: { min: 4000, max: 8000, per: '3 days' },
    nearestCity: { name: 'Kohima', distance: 30, travelTime: '2 hrs + trek' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 3,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Smoked Pork', 'Axone', 'Bamboo Shoot Curry', 'Rice Beer'],
    activities: ['Trekking', 'Camping', 'Flower Photography', 'Bird Watching'],
    gradient: 'linear-gradient(135deg, #4C1D95 0%, #8B5CF6 50%, #DDD6FE 100%)',
    emoji: '🌸'
  },
  {
    id: 'nongriat',
    name: 'Nongriat',
    state: 'Meghalaya',
    region: 'North-East India',
    tagline: 'Double Decker Living Root Bridge',
    description: 'Deep in the Khasi Hills, the village of Nongriat harbors a marvel of bio-engineering — double-decker living root bridges grown over centuries by training the roots of rubber fig trees across streams. The trek down 3,500 stone steps through lush subtropical forest to reach these bridges is an adventure in itself.',
    localInsight: 'Start early morning to beat the heat on the climb back up. The natural pool beneath the double-decker bridge is perfect for a refreshing swim. Stay overnight at a local homestay to experience the bridge at sunrise without crowds.',
    coordinates: { lat: 25.2836, lng: 91.7286 },
    categories: ['forests', 'adventure', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'November – April',
    budget: { min: 2500, max: 5000, per: '2 days' },
    nearestCity: { name: 'Shillong', distance: 70, travelTime: '3 hrs + trek' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Jadoh', 'Doh Khleh', 'Ki Kpu', 'Black Sesame Candy'],
    activities: ['Root Bridge Trek', 'Swimming', 'Waterfall Visit', 'Village Stay'],
    gradient: 'linear-gradient(135deg, #064E3B 0%, #047857 50%, #A7F3D0 100%)',
    emoji: '🌳'
  },
  {
    id: 'orchha',
    name: 'Orchha',
    state: 'Madhya Pradesh',
    region: 'Central India',
    tagline: 'Frozen in Medieval Time',
    description: 'Orchha is a forgotten medieval town frozen in time, where magnificent 16th-century Bundela palaces, temples, and cenotaphs stand amid a sleepy town on the Betwa River. Unlike the crowded heritage sites of Rajasthan, Orchha offers the same architectural grandeur with barely any tourists. Vultures nest in the cenotaphs and the river offers peaceful kayaking.',
    localInsight: 'The light and sound show at the fort is beautiful but the real magic is exploring the empty palaces at your own pace during the day. The Jahangir Mahal\'s upper terrace at sunset gives panoramic views that rival any fort in India.',
    coordinates: { lat: 25.3520, lng: 78.6408 },
    categories: ['heritage', 'forts', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 2000, max: 5000, per: '2 days' },
    nearestCity: { name: 'Jhansi', distance: 16, travelTime: '30 min' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Bhutte ka Kees', 'Poha Jalebi', 'Dal Bafla', 'Mawa Bati'],
    activities: ['Palace Exploration', 'River Kayaking', 'Bird Watching', 'Cycling'],
    gradient: 'linear-gradient(135deg, #7C2D12 0%, #C2410C 50%, #FDBA74 100%)',
    emoji: '🏰'
  },
  {
    id: 'bhedaghat',
    name: 'Bhedaghat Marble Rocks',
    state: 'Madhya Pradesh',
    region: 'Central India',
    tagline: 'Marble Canyon on the Narmada',
    description: 'The Narmada River carves through 100-foot-high marble cliffs at Bhedaghat, creating a gorge that glows white and blue in the moonlight. A boat ride through these towering marble walls — especially during full moon nights — is one of India\'s most mesmerizing experiences. The nearby Dhuandhar Falls adds thunder to the beauty.',
    localInsight: 'Take the moonlight boat ride during full moon — the marble glows ethereally. The ropeway across the gorge gives a bird\'s-eye view. Visit Chausath Yogini Temple on the hill for panoramic views of the gorge.',
    coordinates: { lat: 23.1094, lng: 79.7928 },
    categories: ['waterfalls', 'photography', 'adventure'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Jabalpur', distance: 25, travelTime: '45 min' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Bhutte ka Kees', 'Sabudana Khichdi', 'Poha', 'Malpua'],
    activities: ['Boat Ride', 'Waterfall Visit', 'Ropeway', 'Temple Visit'],
    gradient: 'linear-gradient(135deg, #E0F2FE 0%, #BAE6FD 50%, #0EA5E9 100%)',
    emoji: '💎'
  },
  {
    id: 'dhanushkodi',
    name: 'Dhanushkodi',
    state: 'Tamil Nadu',
    region: 'South India',
    tagline: 'The Ghost Town at Land\'s End',
    description: 'Dhanushkodi is an abandoned town at the tip of Rameswaram island, destroyed by a cyclone in 1964. The ruins of the railway station, church, and post office sit where the Bay of Bengal meets the Indian Ocean. The narrow strip of land stretching into the sea with turquoise waters on both sides is hauntingly beautiful.',
    localInsight: 'Go early morning to avoid the heat. The jeep ride through the sand to the tip is thrilling. At the very end, you can see Sri Lanka on clear days. The local fishermen tell fascinating stories about life before the cyclone.',
    coordinates: { lat: 9.1720, lng: 79.4268 },
    categories: ['beaches', 'heritage', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – April',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Rameswaram', distance: 20, travelTime: '1 hr' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Chettinad Chicken', 'Appam', 'Fish Curry', 'Kothu Parotta'],
    activities: ['Ghost Town Walk', 'Beach Visit', 'Sea View Point', 'Photography'],
    gradient: 'linear-gradient(135deg, #164E63 0%, #0891B2 50%, #A5F3FC 100%)',
    emoji: '🌊'
  },
  {
    id: 'tirthan-valley',
    name: 'Tirthan Valley',
    state: 'Himachal Pradesh',
    region: 'North India',
    tagline: 'Gateway to Great Himalayan National Park',
    description: 'Tirthan Valley is a pristine paradise named after the Tirthan River, a tributary of the Beas. It\'s the gateway to the UNESCO-listed Great Himalayan National Park. Crystal-clear trout streams, old-growth forests, and traditional Himachali villages untouched by mass tourism make this valley a dream for nature lovers.',
    localInsight: 'Try trout fishing in the Tirthan River (catch and release) — the river is teeming with brown trout. Stay at Raju\'s cottage for the most authentic homestay experience. The Jalori Pass trek offers stunning views with minimal effort.',
    coordinates: { lat: 31.6350, lng: 77.4000 },
    categories: ['mountains', 'forests', 'adventure'],
    difficulty: 'Easy',
    bestSeason: 'March – June, Sep – Nov',
    budget: { min: 4000, max: 8000, per: '3 days' },
    nearestCity: { name: 'Kullu', distance: 50, travelTime: '2 hrs' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Trout Fish', 'Siddu', 'Dham', 'Babru'],
    activities: ['Trout Fishing', 'Trekking', 'River Crossing', 'Bird Watching'],
    gradient: 'linear-gradient(135deg, #0D4F4F 0%, #14B8A6 50%, #99F6E4 100%)',
    emoji: '🎣'
  },
  {
    id: 'lonar',
    name: 'Lonar Crater Lake',
    state: 'Maharashtra',
    region: 'West India',
    tagline: 'Meteor Impact Lake – 50,000 Years Old',
    description: 'Lonar Lake is the world\'s third-largest crater formed by a meteorite impact around 50,000 years ago. This unique saline-alkaline lake sits in a nearly circular basin, surrounded by ancient temples and lush forest. The lake\'s water turns pink due to algae blooms, creating a surreal landscape that feels more like Mars than Maharashtra.',
    localInsight: 'Visit the Daitya Sudan temple at the crater rim — it\'s an architectural gem from the Chalukya period. The walk around the crater takes about 3-4 hours and passes through several hidden temples.',
    coordinates: { lat: 19.9760, lng: 76.5067 },
    categories: ['lakes', 'heritage', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – February',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Aurangabad', distance: 150, travelTime: '3.5 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Varan Bhaat', 'Misal Pav', 'Puran Poli', 'Thalipeeth'],
    activities: ['Crater Walk', 'Temple Visits', 'Bird Watching', 'Photography'],
    gradient: 'linear-gradient(135deg, #701A75 0%, #C026D3 50%, #F0ABFC 100%)',
    emoji: '☄️'
  },
  {
    id: 'jawai',
    name: 'Jawai Leopard Hills',
    state: 'Rajasthan',
    region: 'West India',
    tagline: 'Where Leopards Roam Among People',
    description: 'Jawai is perhaps the only place in the world where leopards and humans coexist peacefully. The granite hills harbor a healthy leopard population that the Rabari tribespeople have protected for generations. Unlike national parks, leopard sightings here happen on open hilltops against dramatic pink granite landscapes — no jungle jeep safaris, just pure raw nature.',
    localInsight: 'Go on a dawn safari with a local Rabari guide — they know every leopard by name. The Jawai Dam attracts thousands of migratory flamingos in winter. Visit the Rabari settlements to learn about their fascinating semi-nomadic culture.',
    coordinates: { lat: 25.1350, lng: 73.1900 },
    categories: ['wildlife', 'photography', 'adventure'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 6000, max: 15000, per: '2 days' },
    nearestCity: { name: 'Udaipur', distance: 130, travelTime: '2.5 hrs' },
    ageGroups: ['young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Dal Baati Churma', 'Laal Maas', 'Ker Sangri', 'Ghewar'],
    activities: ['Leopard Safari', 'Flamingo Watching', 'Tribal Visit', 'Photography'],
    gradient: 'linear-gradient(135deg, #451A03 0%, #B45309 50%, #FCD34D 100%)',
    emoji: '🐆'
  },
  {
    id: 'muzhappilangad',
    name: 'Muzhappilangad Beach',
    state: 'Kerala',
    region: 'South India',
    tagline: 'Asia\'s Longest Drive-in Beach',
    description: 'Stretching 4 kilometers along the Malabar coast, Muzhappilangad is Asia\'s longest drive-in beach. Unlike the crowded beaches of Goa, this dark-sand beach is pristine and almost empty. You can drive your car or bike right along the waterline, with the Arabian Sea waves lapping at your tires. The dramatic black rocks at one end and the fishing village at the other create a unique coastal experience.',
    localInsight: 'Drive along the beach during low tide for the best experience. The Dharmadam Island visible offshore is a protected biodiversity spot. Try the fresh Malabar fish fry at the small shacks near the northern end.',
    coordinates: { lat: 11.8133, lng: 75.3817 },
    categories: ['beaches', 'adventure', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – May',
    budget: { min: 2000, max: 5000, per: '2 days' },
    nearestCity: { name: 'Kannur', distance: 15, travelTime: '30 min' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 5,
    photoScore: 4,
    popularity: 'Low',
    foods: ['Malabar Biryani', 'Fish Curry', 'Pathiri', 'Unnakaya'],
    activities: ['Beach Driving', 'Swimming', 'Island Viewing', 'Seafood Trail'],
    gradient: 'linear-gradient(135deg, #155E75 0%, #0891B2 50%, #67E8F9 100%)',
    emoji: '🚗'
  },
  {
    id: 'kaas-plateau',
    name: 'Kaas Plateau',
    state: 'Maharashtra',
    region: 'West India',
    tagline: 'Maharashtra\'s Valley of Flowers',
    description: 'Known as the "Valley of Flowers of the West", Kaas Plateau is a UNESCO Natural World Heritage Site that transforms into a colorful carpet of wildflowers during monsoon. Over 850 species of flowering plants bloom here between August and October, creating a stunning visual spectacle against the backdrop of the Western Ghats.',
    localInsight: 'Visit in late September for peak bloom. Entry is restricted to 3000 visitors per day — book online. The Kaas Lake nearby has beautiful reflections during early morning. Walk gently on the designated paths; many flowers are micro-endemic.',
    coordinates: { lat: 17.7215, lng: 73.8084 },
    categories: ['photography', 'forests'],
    difficulty: 'Easy',
    bestSeason: 'August – October',
    budget: { min: 2000, max: 4000, per: '1 day' },
    nearestCity: { name: 'Satara', distance: 25, travelTime: '45 min' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Misal Pav', 'Pithla Bhakri', 'Tambda Rassa', 'Puran Poli'],
    activities: ['Wildflower Walk', 'Photography', 'Lake Visit', 'Nature Trail'],
    gradient: 'linear-gradient(135deg, #581C87 0%, #A855F7 50%, #E9D5FF 100%)',
    emoji: '🌺'
  },
  {
    id: 'mandu',
    name: 'Mandu',
    state: 'Madhya Pradesh',
    region: 'Central India',
    tagline: 'City of Joy – Romance in Ruins',
    description: 'Perched on the Vindhya Range at 2,000 feet, Mandu is a ruined city steeped in the love story of Sultan Baz Bahadur and Rani Roopmati. Afghan and Mughal architecture blend beautifully with the natural terrain — palaces have natural pools, pavilions float over ravines, and the Jahaz Mahal appears to float between two lakes.',
    localInsight: 'Visit Roopmati\'s Pavilion at sunset — you can see the silver thread of the Narmada River from the clifftop. During monsoon, the baobab trees bloom, the lakes fill up, and Jahaz Mahal truly looks like a ship sailing between lakes.',
    coordinates: { lat: 22.3676, lng: 75.3894 },
    categories: ['heritage', 'forts', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'July – March',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Indore', distance: 100, travelTime: '2.5 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Poha Jalebi', 'Bhutte ka Kees', 'Dal Bafla', 'Malpua'],
    activities: ['Palace Exploration', 'Cycling', 'Photography', 'Sunset Viewing'],
    gradient: 'linear-gradient(135deg, #7C2D12 0%, #EA580C 50%, #FED7AA 100%)',
    emoji: '💕'
  },
  {
    id: 'tawang',
    name: 'Tawang',
    state: 'Arunachal Pradesh',
    region: 'North-East India',
    tagline: 'India\'s Most Dramatic Monastery Town',
    description: 'Tawang sits at 10,000 feet surrounded by snow-capped peaks and houses India\'s largest Buddhist monastery — the 400-year-old Tawang Monastery. The drive to Tawang through Sela Pass (13,700 ft) with its glacial lakes is one of India\'s most thrilling road journeys. Tibetan Buddhist culture, yak herds, and pristine alpine meadows make this a destination like no other.',
    localInsight: 'Cross Sela Pass early morning when the Sela Lake is mirror-still. In the monastery, attend the morning prayers with the monks. The Tawang War Memorial at dusk is deeply moving — the light and sound show narrates the 1962 India-China war.',
    coordinates: { lat: 27.5859, lng: 91.8686 },
    categories: ['mountains', 'temples', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'March – October',
    budget: { min: 8000, max: 15000, per: '4 days' },
    nearestCity: { name: 'Guwahati', distance: 480, travelTime: '14 hrs' },
    ageGroups: ['young-professionals'],
    safetyRating: 3,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Thukpa', 'Momos', 'Zan', 'Butter Tea', 'Khura'],
    activities: ['Monastery Visit', 'Sela Pass Drive', 'War Memorial', 'Lake Visit'],
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #6366F1 50%, #C7D2FE 100%)',
    emoji: '🕉️'
  },
  {
    id: 'bundi',
    name: 'Bundi',
    state: 'Rajasthan',
    region: 'West India',
    tagline: 'The City of Stepwells & Miniature Paintings',
    description: 'Bundi is Rajasthan\'s best-kept secret — a blue-washed town nestled in a narrow valley, with a massive palace complex perched above. Famous for its stunning step wells (baoris), intricate miniature paintings inside the palace, and a fort that Rudyard Kipling described as the work of goblins rather than men.',
    localInsight: 'Visit Raniji ki Baori — it\'s the most ornate stepwell in Rajasthan with beautiful carvings. The Chitrashala inside Bundi Palace has miniature paintings that rival Ajanta. Stay near the Nawal Sagar lake for dreamy reflections of the palace.',
    coordinates: { lat: 25.4305, lng: 75.6499 },
    categories: ['heritage', 'forts', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 2000, max: 5000, per: '2 days' },
    nearestCity: { name: 'Jaipur', distance: 210, travelTime: '4 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Dal Baati Churma', 'Ghewar', 'Kachori', 'Lassi'],
    activities: ['Stepwell Visit', 'Palace Tour', 'Fort Trek', 'Photography Walk'],
    gradient: 'linear-gradient(135deg, #1E3A8A 0%, #3B82F6 50%, #BFDBFE 100%)',
    emoji: '💙'
  },
  {
    id: 'valparai',
    name: 'Valparai',
    state: 'Tamil Nadu',
    region: 'South India',
    tagline: 'Misty Tea Plantations & Wildlife',
    description: 'Valparai is an enchanting hill station perched atop the Anamalai Hills in the Western Ghats. Surrounded by vast tea and coffee plantations, this small town is a haven for wildlife — lion-tailed macaques, elephants, and hornbills are commonly spotted. The drive up through 40 hairpin bends with waterfalls at every turn is spectacular.',
    localInsight: 'Drive slowly on the ghat road — wild elephants frequently cross. Nallamudi viewpoint offers stunning sunrise views above the clouds. Try the fresh estate coffee at Kanan Devan plantation — it\'s liquid gold.',
    coordinates: { lat: 10.3269, lng: 76.9695 },
    categories: ['mountains', 'wildlife', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'September – May',
    budget: { min: 3000, max: 6000, per: '2 days' },
    nearestCity: { name: 'Coimbatore', distance: 100, travelTime: '3.5 hrs' },
    ageGroups: ['young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Filter Coffee', 'Dosa', 'Kothu Parotta', 'Banana Bonda'],
    activities: ['Plantation Walk', 'Wildlife Spotting', 'Viewpoint Visits', 'Waterfall Visit'],
    gradient: 'linear-gradient(135deg, #14532D 0%, #16A34A 50%, #BBF7D0 100%)',
    emoji: '🍃'
  },
  {
    id: 'chitrakote-falls',
    name: 'Chitrakote Falls',
    state: 'Chhattisgarh',
    region: 'Central India',
    tagline: 'The Niagara Falls of India',
    description: 'Chitrakote Falls on the Indravati River is India\'s widest waterfall, spanning nearly 300 meters during monsoon. Often called the Niagara of India, this horseshoe-shaped waterfall plunges 30 meters into a misty pool. Despite its grandeur, it remains one of India\'s least-visited waterfalls due to Chhattisgarh being off the mainstream tourist circuit.',
    localInsight: 'Visit during late monsoon (August-September) when the falls are at full power. Take the boat ride to the base — the mist and rainbow are incredible. The Tirathgarh Falls nearby is equally stunning and far less crowded.',
    coordinates: { lat: 19.2068, lng: 81.7018 },
    categories: ['waterfalls', 'photography', 'adventure'],
    difficulty: 'Easy',
    bestSeason: 'July – October',
    budget: { min: 3000, max: 6000, per: '2 days' },
    nearestCity: { name: 'Jagdalpur', distance: 40, travelTime: '1 hr' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Chapra Chutney', 'Muthia', 'Fara', 'Angakar Roti'],
    activities: ['Waterfall Viewing', 'Boat Ride', 'Photography', 'Tribal Village Visit'],
    gradient: 'linear-gradient(135deg, #0C4A6E 0%, #0284C7 50%, #7DD3FC 100%)',
    emoji: '🌊'
  },
  {
    id: 'sandakphu',
    name: 'Sandakphu',
    state: 'West Bengal',
    region: 'East India',
    tagline: 'Sleeping Buddha View of Four Highest Peaks',
    description: 'At 11,941 feet, Sandakphu is the highest peak in West Bengal and offers a view found nowhere else — four of the world\'s five highest peaks (Everest, Kanchenjunga, Lhotse, and Makalu) visible in a single panoramic frame. The Kanchenjunga massif creates the famous "Sleeping Buddha" silhouette against the dawn sky.',
    localInsight: 'The best views are at dawn — get up at 4 AM and climb to the viewpoint. The trek from Manebhanjan takes 3 days and passes through Nepali and Sherpa villages. Land Rovers also go up for non-trekkers.',
    coordinates: { lat: 27.1028, lng: 88.0014 },
    categories: ['mountains', 'adventure', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'October – December, March – May',
    budget: { min: 5000, max: 10000, per: '4 days' },
    nearestCity: { name: 'Darjeeling', distance: 55, travelTime: '6 hrs (trek)' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Momos', 'Thukpa', 'Sel Roti', 'Churpi Soup'],
    activities: ['Trekking', 'Sunrise Viewing', 'Photography', 'Village Stays'],
    gradient: 'linear-gradient(135deg, #312E81 0%, #6366F1 50%, #C7D2FE 100%)',
    emoji: '🗻'
  },
  {
    id: 'loktak-lake',
    name: 'Loktak Lake',
    state: 'Manipur',
    region: 'North-East India',
    tagline: 'Floating Islands & Endangered Deer',
    description: 'Loktak Lake is the largest freshwater lake in Northeast India, famous for its phumdis — floating masses of vegetation that serve as habitats for the endangered Sangai deer, also known as the dancing deer. The Keibul Lamjao National Park, the only floating national park in the world, sits on these phumdis.',
    localInsight: 'Take a boat ride to the phumdis and ask the fisherman to show you the Sangai deer grazing spots. The floating huts of local fishermen are an incredible sight. Visit Sendra Island for a panoramic view of the entire lake.',
    coordinates: { lat: 24.5580, lng: 93.7860 },
    categories: ['lakes', 'wildlife', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – February',
    budget: { min: 3000, max: 6000, per: '2 days' },
    nearestCity: { name: 'Imphal', distance: 48, travelTime: '1.5 hrs' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Eromba', 'Chamthong', 'Singju', 'Kangshoi'],
    activities: ['Boat Ride', 'Sangai Spotting', 'Island Visit', 'Photography'],
    gradient: 'linear-gradient(135deg, #065F46 0%, #0D9488 50%, #99F6E4 100%)',
    emoji: '🦌'
  },
  {
    id: 'athirapally',
    name: 'Athirapally Falls',
    state: 'Kerala',
    region: 'South India',
    tagline: 'The Bahubali Waterfall of India',
    description: 'Athirapally Falls is Kerala\'s largest waterfall, plunging 80 feet from the Sholayar ranges into the Chalakudy River. Featured in the Bollywood blockbuster Bahubali, this majestic falls is surrounded by dense tropical rainforest. The viewing platforms offer spectacular views, and the surrounding forest trails lead to more hidden cascades.',
    localInsight: 'Visit during monsoon (June-September) when the falls are at their most powerful — over 130 feet wide. The early morning visit avoids crowds. Don\'t miss Vazhachal Falls just 5 km upstream. The forest around has hornbills and Malabar giant squirrels.',
    coordinates: { lat: 10.2856, lng: 76.5697 },
    categories: ['waterfalls', 'forests', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'June – January',
    budget: { min: 2000, max: 5000, per: '1 day' },
    nearestCity: { name: 'Thrissur', distance: 60, travelTime: '1.5 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Kerala Sadya', 'Fish Curry', 'Appam Stew', 'Puttu Kadala'],
    activities: ['Waterfall Viewing', 'Nature Walk', 'Bird Watching', 'Photography'],
    gradient: 'linear-gradient(135deg, #0F4C3A 0%, #059669 50%, #6EE7B7 100%)',
    emoji: '⛲'
  },
  {
    id: 'chettinad',
    name: 'Chettinad',
    state: 'Tamil Nadu',
    region: 'South India',
    tagline: 'Palatial Mansions & Fiery Cuisine',
    description: 'Chettinad is a cluster of 75 villages known for their stunning Nattukotai Chettiar mansions — grand ancestral homes built with materials sourced from around the world. Burmese teak, Italian marble, Belgian glass, and Scottish iron all find place in these opulent structures. The region is equally famous for its fiery Chettinad cuisine.',
    localInsight: 'Many mansions are now heritage hotels — stay in one for the full experience. Visit the antique shops in Karaikudi for unique finds. The Chettinad kitchen is intense — request moderate spice levels if you\'re not used to it!',
    coordinates: { lat: 10.1700, lng: 78.7800 },
    categories: ['heritage', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 3000, max: 8000, per: '2 days' },
    nearestCity: { name: 'Madurai', distance: 80, travelTime: '2 hrs' },
    ageGroups: ['young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Chettinad Chicken', 'Kavuni Arisi', 'Kuzhi Paniyaram', 'Appam'],
    activities: ['Mansion Tours', 'Cooking Class', 'Antique Shopping', 'Temple Visit'],
    gradient: 'linear-gradient(135deg, #7C2D12 0%, #DC2626 50%, #FCA5A5 100%)',
    emoji: '🏠'
  },
  {
    id: 'phugtal',
    name: 'Phugtal Monastery',
    state: 'Ladakh',
    region: 'North India',
    tagline: 'Cave Monastery at World\'s Edge',
    description: 'Phugtal Gompa is one of the most spectacularly located monasteries in the world, built into a massive cave on a cliff face above the Tsarap River in Zanskar. Accessible only by a multi-day trek or arduous drive, this 12th-century monastery houses monks who live in near-total isolation, preserving ancient Buddhist traditions.',
    localInsight: 'The 2-day trek from Purne village is the most common approach. Carry supplies as there are no shops. The monks are incredibly welcoming and will share their simple meals. The sacred spring inside the cave is believed to have healing properties.',
    coordinates: { lat: 33.4000, lng: 76.9500 },
    categories: ['temples', 'adventure', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'June – September',
    budget: { min: 10000, max: 20000, per: '5 days' },
    nearestCity: { name: 'Padum', distance: 60, travelTime: '2 days (trek)' },
    ageGroups: ['young-professionals'],
    safetyRating: 3,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Thukpa', 'Skyu', 'Butter Tea', 'Tsampa'],
    activities: ['Trekking', 'Monastery Visit', 'Meditation', 'Photography'],
    gradient: 'linear-gradient(135deg, #44403C 0%, #78716C 50%, #D6D3D1 100%)',
    emoji: '🧘'
  },
  {
    id: 'shettihalli',
    name: 'Shettihalli Church',
    state: 'Karnataka',
    region: 'South India',
    tagline: 'The Submerged Gothic Church',
    description: 'The Shettihalli Rosary Church is a hauntingly beautiful French-Gothic church that gets partially submerged every monsoon when the Hemavathi Reservoir rises. Built by French missionaries in the 1860s, the church was abandoned when the reservoir was built. Today, its skeleton rising from the waters creates one of India\'s most surreal and photogenic sights.',
    localInsight: 'Visit during late monsoon (August-September) when the water level is highest and the church is half-submerged. Early morning mist adds an ethereal quality. You can kayak to the church during high water levels.',
    coordinates: { lat: 13.0300, lng: 76.0200 },
    categories: ['heritage', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'August – November',
    budget: { min: 1500, max: 3000, per: '1 day' },
    nearestCity: { name: 'Hassan', distance: 22, travelTime: '40 min' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Ragi Mudde', 'Akki Rotti', 'Bisi Bele Bath', 'Mysore Pak'],
    activities: ['Photography', 'Kayaking', 'Exploration', 'Bird Watching'],
    gradient: 'linear-gradient(135deg, #374151 0%, #6B7280 50%, #D1D5DB 100%)',
    emoji: '⛪'
  },
  {
    id: 'dholavira',
    name: 'Dholavira',
    state: 'Gujarat',
    region: 'West India',
    tagline: 'Harappan City in the White Desert',
    description: 'Dholavira is one of the five largest Harappan/Indus Valley Civilization sites and the most remarkable one in India. Located on the Khadir Bet island in the Great Rann of Kutch, this UNESCO World Heritage Site reveals a 4,500-year-old city with sophisticated water management, massive stone gateways, and the world\'s earliest known signboard.',
    localInsight: 'Visit the museum first for context, then explore the excavated city. The journey through the white Rann desert to reach Dholavira is an experience in itself. Stay overnight to see the star-filled sky — there\'s zero light pollution.',
    coordinates: { lat: 23.8878, lng: 70.2100 },
    categories: ['heritage', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'October – March',
    budget: { min: 3000, max: 6000, per: '2 days' },
    nearestCity: { name: 'Bhuj', distance: 250, travelTime: '6 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 4,
    photoScore: 4,
    popularity: 'Low',
    foods: ['Dhokla', 'Dabeli', 'Kutchi Dabeli', 'Bajra Rotla'],
    activities: ['Archaeological Tour', 'Museum Visit', 'Desert Drive', 'Stargazing'],
    gradient: 'linear-gradient(135deg, #A16207 0%, #D97706 50%, #FDE68A 100%)',
    emoji: '🏺'
  },
  {
    id: 'araku-valley',
    name: 'Araku Valley',
    state: 'Andhra Pradesh',
    region: 'South India',
    tagline: 'Coffee Plantations in Eastern Ghats',
    description: 'Araku Valley is a hidden gem in the Eastern Ghats, known for its award-winning coffee, tribal culture, and breathtaking landscapes. The valley is home to several indigenous tribes who cultivate Arabica coffee that has won international acclaim. The train journey from Visakhapatnam through 46 tunnels and across numerous bridges is considered one of India\'s most scenic rail routes.',
    localInsight: 'Take the early morning Kirandul Express from Vizag for the most scenic train journey. Visit the Tribal Museum to understand the rich Adivasi culture. Buy the local Araku Valley coffee — it\'s won international awards.',
    coordinates: { lat: 18.3274, lng: 82.8755 },
    categories: ['mountains', 'heritage', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 2500, max: 5000, per: '2 days' },
    nearestCity: { name: 'Visakhapatnam', distance: 114, travelTime: '3 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 4,
    popularity: 'Low',
    foods: ['Bamboo Chicken', 'Bongulo Chicken', 'Pootharekulu', 'Araku Coffee'],
    activities: ['Train Journey', 'Coffee Plantation Tour', 'Cave Visit', 'Tribal Museum'],
    gradient: 'linear-gradient(135deg, #3F6212 0%, #65A30D 50%, #BEF264 100%)',
    emoji: '☕'
  },
  {
    id: 'ponmudi',
    name: 'Ponmudi',
    state: 'Kerala',
    region: 'South India',
    tagline: 'The Golden Peak of Kerala',
    description: 'Ponmudi, meaning "Golden Peak", is a lesser-known hill station near Trivandrum, nestled among the Western Ghats. The winding road with 22 hairpin bends passes through tea gardens, streams, and mist-covered forests. At the top, the Peppara Wildlife Sanctuary and its varied terrain of grasslands, forests, and waterfalls awaits.',
    localInsight: 'The Golden Valley viewpoint offers the best panoramic view. Drive up early to catch the clouds rolling through the valleys. The small trek to Meenmutty Falls is worth it. Try the local tea at the hilltop estate.',
    coordinates: { lat: 8.7599, lng: 77.1191 },
    categories: ['mountains', 'wildlife', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'September – May',
    budget: { min: 2000, max: 4000, per: '1 day' },
    nearestCity: { name: 'Trivandrum', distance: 61, travelTime: '2 hrs' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 5,
    photoScore: 4,
    popularity: 'Low',
    foods: ['Kerala Porotta', 'Beef Fry', 'Fish Molee', 'Banana Chips'],
    activities: ['Scenic Drive', 'Trekking', 'Waterfall Visit', 'Wildlife Spotting'],
    gradient: 'linear-gradient(135deg, #14532D 0%, #15803D 50%, #86EFAC 100%)',
    emoji: '🌄'
  },
  {
    id: 'lambasingi',
    name: 'Lambasingi',
    state: 'Andhra Pradesh',
    region: 'South India',
    tagline: 'Kashmir of Andhra Pradesh',
    description: 'Lambasingi is a tiny tribal hamlet perched at 1,000 meters in the Eastern Ghats, known as the only place in South India where temperatures drop to near-freezing levels. Morning mist blankets the valley creating a dreamlike atmosphere. Pepper and coffee plantations surround this off-grid hamlet that has no hotels — just the warmth of tribal homestays.',
    localInsight: 'Arrive before dawn to witness the famous fog rolling through the valley. The Kothapalli Waterfalls nearby are stunning during monsoon. This is a no-network zone — embrace the digital detox!',
    coordinates: { lat: 17.8211, lng: 82.6653 },
    categories: ['mountains', 'villages', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'November – February',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Visakhapatnam', distance: 100, travelTime: '3 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 3,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Bamboo Chicken', 'Peanut Chutney', 'Ragi Sangati', 'Pulihora'],
    activities: ['Sunrise Viewing', 'Plantation Walk', 'Waterfall Trek', 'Stargazing'],
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #6366F1 50%, #E0E7FF 100%)',
    emoji: '🌫️'
  },
  {
    id: 'pattadakal',
    name: 'Pattadakal',
    state: 'Karnataka',
    region: 'South India',
    tagline: 'UNESCO Temple Complex of the Chalukyas',
    description: 'Pattadakal is a UNESCO World Heritage group of 8th-century Chalukyan temples that beautifully blend North Indian Nagara and South Indian Dravidian architectural styles. Just 22 km from Badami and near Aihole, these three sites form the "Cradle of Indian Temple Architecture". Unlike Hampi, Pattadakal sees very few tourists despite its immense historical significance.',
    localInsight: 'Visit all three — Aihole, Badami, and Pattadakal — in a single day. Start with Aihole (earliest temples), then Badami (cave temples and rock-cut art), ending at Pattadakal (the most refined). The Virupaksha Temple here predates the one at Hampi.',
    coordinates: { lat: 15.9468, lng: 75.8150 },
    categories: ['heritage', 'temples', 'photography'],
    difficulty: 'Easy',
    bestSeason: 'October – February',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Hubli', distance: 140, travelTime: '3 hrs' },
    ageGroups: ['students', 'young-professionals', 'families', 'seniors'],
    safetyRating: 5,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Jolada Rotti', 'Enne Badnekayi', 'Girmit', 'Dharwad Pedha'],
    activities: ['Temple Exploration', 'Cave Temple Visit', 'Architecture Study', 'Photography'],
    gradient: 'linear-gradient(135deg, #92400E 0%, #D97706 50%, #FEF3C7 100%)',
    emoji: '🛕'
  },
  {
    id: 'mechuka',
    name: 'Mechuka',
    state: 'Arunachal Pradesh',
    region: 'North-East India',
    tagline: 'Shangri-La of India',
    description: 'Mechuka is a remote valley at 6,000 feet called the Shangri-La of India. Surrounded by snow-capped mountains, with the Siyom River flowing through, this valley near the China border was unknown to the outside world until recently. The Adi and Memba tribes here practice unique customs, and a 400-year-old Buddhist monastery adds spiritual depth.',
    localInsight: 'The road journey from Along is an adventure itself — 6 hours through dramatic terrain. The Samten Yongcha monastery offers meditation retreats. Visit the hanging bridge over the Siyom River and interact with the friendly Memba villagers.',
    coordinates: { lat: 28.6200, lng: 94.0900 },
    categories: ['mountains', 'villages', 'adventure'],
    difficulty: 'Hard',
    bestSeason: 'March – May, Oct – Nov',
    budget: { min: 8000, max: 15000, per: '4 days' },
    nearestCity: { name: 'Along', distance: 185, travelTime: '7 hrs' },
    ageGroups: ['young-professionals'],
    safetyRating: 3,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Apong (Rice Beer)', 'Pika Pila', 'Lukter', 'Bamboo Shoot Curry'],
    activities: ['Valley Exploration', 'Monastery Visit', 'River Crossing', 'Tribal Culture'],
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #0EA5E9 50%, #BAE6FD 100%)',
    emoji: '🏔️'
  },
  {
    id: 'kanatal',
    name: 'Kanatal',
    state: 'Uttarakhand',
    region: 'North India',
    tagline: 'Apple Orchards & Himalayan Serenity',
    description: 'Kanatal is a tiny hamlet near Mussoorie that remains beautifully unspoiled. At 8,500 feet, it offers panoramic views of the Himalayas, dense deodar and oak forests, and apple orchards. Unlike crowded hill stations, Kanatal offers pure solitude — no markets, no traffic, just birdsong and mountain air.',
    localInsight: 'The Kodia Jungle trek offers a challenging but rewarding walk through dense forest. Stay at a camp for the best experience — the stargazing from here is incredible. Visit Surkanda Devi Temple for a short trek with grand views.',
    coordinates: { lat: 30.4400, lng: 78.3600 },
    categories: ['mountains', 'forests', 'adventure'],
    difficulty: 'Easy',
    bestSeason: 'March – June, Sep – Nov',
    budget: { min: 4000, max: 8000, per: '2 days' },
    nearestCity: { name: 'Mussoorie', distance: 38, travelTime: '1.5 hrs' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 5,
    photoScore: 4,
    popularity: 'Low',
    foods: ['Mandua Roti', 'Kafuli', 'Chainsoo', 'Bal Mithai'],
    activities: ['Camping', 'Jungle Trek', 'Stargazing', 'Temple Trek'],
    gradient: 'linear-gradient(135deg, #166534 0%, #22C55E 50%, #BBF7D0 100%)',
    emoji: '🍎'
  },
  {
    id: 'kalpa',
    name: 'Kalpa',
    state: 'Himachal Pradesh',
    region: 'North India',
    tagline: 'Face to Face with Kinner Kailash',
    description: 'Kalpa is a small town in the Kinnaur district that sits directly across from the sacred Kinner Kailash peak (6,500m). The sunrise here — when the massive peak glows from pink to gold to white — is one of the most breathtaking mountain views in India. Ancient temples, apple orchards, and traditional Kinnauri houses complete the enchantment.',
    localInsight: 'Book a hotel with a Kinner Kailash view and watch the peak change colors at sunrise from your bed. The Roghi village walk through apple orchards is delightful in September-October during harvest season. The Narayan-Nagini Temple has exquisite wood carvings.',
    coordinates: { lat: 31.5310, lng: 78.2530 },
    categories: ['mountains', 'temples', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'March – June, Sep – Nov',
    budget: { min: 4000, max: 8000, per: '2 days' },
    nearestCity: { name: 'Shimla', distance: 260, travelTime: '9 hrs' },
    ageGroups: ['students', 'young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Siddu', 'Dham', 'Kinnauri Rajma', 'Chilra', 'Apple Wine'],
    activities: ['Sunrise Watching', 'Village Walk', 'Temple Visit', 'Apple Orchard'],
    gradient: 'linear-gradient(135deg, #7C2D12 0%, #F97316 50%, #FFEDD5 100%)',
    emoji: '🌅'
  },
  {
    id: 'lepchajagat',
    name: 'Lepchajagat',
    state: 'West Bengal',
    region: 'East India',
    tagline: 'Misty Forest Hamlet Near Darjeeling',
    description: 'Lepchajagat is a fog-wrapped hamlet at 6,956 feet, just 19 km from Darjeeling but a world away in atmosphere. Dense forests of oak, birch, and magnolia, with zero commercialization, make this the perfect escape. The forest walks here during monsoon, with mist rolling through the trees and birdsong everywhere, are hauntingly beautiful.',
    localInsight: 'There\'s essentially one forest bungalow — book early. The walk to Hawa Ghar viewpoint on a clear day reveals Kanchenjunga in full glory. Night walks with a flashlight reveal flying squirrels and rare moths. Bring warm clothes even in summer.',
    coordinates: { lat: 27.0100, lng: 88.2100 },
    categories: ['forests', 'photography', 'wildlife'],
    difficulty: 'Easy',
    bestSeason: 'October – March',
    budget: { min: 2000, max: 4000, per: '2 days' },
    nearestCity: { name: 'Darjeeling', distance: 19, travelTime: '1 hr' },
    ageGroups: ['young-professionals', 'families'],
    safetyRating: 4,
    photoScore: 4,
    popularity: 'Low',
    foods: ['Momos', 'Thukpa', 'Darjeeling Tea', 'Sel Roti'],
    activities: ['Forest Walks', 'Bird Watching', 'Photography', 'Stargazing'],
    gradient: 'linear-gradient(135deg, #14532D 0%, #166534 50%, #BBF7D0 100%)',
    emoji: '🌲'
  },
  {
    id: 'munsiyari',
    name: 'Munsiyari',
    state: 'Uttarakhand',
    region: 'North India',
    tagline: 'Little Kashmir of Kumaon',
    description: 'Munsiyari is an unspoiled gem at the edge of the Johar Valley, offering direct views of the magnificent Panchachuli peaks (five peaks resembling cooking hearths). Once a major trade route to Tibet, this town is surrounded by dense forests, high-altitude meadows, and glacial rivers. It\'s the base for several off-beat Himalayan treks.',
    localInsight: 'The Khaliya Top trek (3 hrs) gives 360° Himalayan views — including Nanda Devi. Visit the Tribal Heritage Museum run by a retired schoolteacher. The drive along the Gori Ganga river valley to reach Munsiyari is breathtaking.',
    coordinates: { lat: 30.0660, lng: 80.2392 },
    categories: ['mountains', 'adventure', 'photography'],
    difficulty: 'Moderate',
    bestSeason: 'March – June, Sep – Nov',
    budget: { min: 4000, max: 8000, per: '3 days' },
    nearestCity: { name: 'Haldwani', distance: 275, travelTime: '10 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Low',
    foods: ['Bhatt ki Churkani', 'Aloo ke Gutke', 'Mandua Roti', 'Jhangora Kheer'],
    activities: ['Khaliya Top Trek', 'Village Walk', 'Museum Visit', 'Photography'],
    gradient: 'linear-gradient(135deg, #1E3A5F 0%, #3B82F6 50%, #DBEAFE 100%)',
    emoji: '🏕️'
  },
  {
    id: 'nubra-valley',
    name: 'Nubra Valley',
    state: 'Ladakh',
    region: 'North India',
    tagline: 'Sand Dunes & Double-Humped Camels',
    description: 'Nubra Valley, reached by crossing the world\'s highest motorable pass Khardung La (18,380 ft), is a surreal landscape where cold desert sand dunes exist alongside the Shyok River. Double-humped Bactrian camels roam the white sand dunes at Hunder, creating a scene that seems impossible in the Himalayas.',
    localInsight: 'Camp at Hunder for the sunset camel ride on white sand dunes. Visit Diskit Monastery with its giant Maitreya Buddha statue overlooking the valley. The hot springs at Panamik are a relaxing stop. Drive to Turtuk — the last Indian village before Pakistan.',
    coordinates: { lat: 34.6800, lng: 77.5800 },
    categories: ['mountains', 'adventure', 'photography'],
    difficulty: 'Hard',
    bestSeason: 'June – September',
    budget: { min: 8000, max: 15000, per: '3 days' },
    nearestCity: { name: 'Leh', distance: 120, travelTime: '5 hrs' },
    ageGroups: ['students', 'young-professionals'],
    safetyRating: 4,
    photoScore: 5,
    popularity: 'Medium',
    foods: ['Thukpa', 'Momos', 'Skyu', 'Apricot Jam', 'Butter Tea'],
    activities: ['Camel Safari', 'Monastery Visit', 'Hot Springs', 'Sand Dunes'],
    gradient: 'linear-gradient(135deg, #78350F 0%, #A16207 50%, #FEF3C7 100%)',
    emoji: '🐪'
  },
];

// ========================================
// FOOD DATA by Region
// ========================================
TT.foods = [
  { name: 'Dal Baati Churma', region: 'Rajasthan', type: 'Main Course', emoji: '🫓', description: 'Baked wheat balls served with spicy lentils and sweet crushed wheat — the iconic Rajasthani trinity.', priceRange: '₹80-150', mustTry: true },
  { name: 'Laal Maas', region: 'Rajasthan', type: 'Main Course', emoji: '🍖', description: 'Fiery red meat curry made with mathania chillies — the royal warrior dish of Rajputana.', priceRange: '₹200-350', mustTry: true },
  { name: 'Ghewar', region: 'Rajasthan', type: 'Dessert', emoji: '🍰', description: 'Disc-shaped sweet made of flour soaked in sugar syrup, topped with rabri — the monsoon festival specialty.', priceRange: '₹60-120', mustTry: true },
  { name: 'Thukpa', region: 'Ladakh / Himachal', type: 'Soup', emoji: '🍜', description: 'Warm Tibetan noodle soup with vegetables or meat — the perfect high-altitude comfort food.', priceRange: '₹60-120', mustTry: true },
  { name: 'Momos', region: 'North-East / Himalayas', type: 'Snack', emoji: '🥟', description: 'Steamed dumplings with minced filling — the universal mountain comfort food from Ladakh to Sikkim.', priceRange: '₹40-100', mustTry: true },
  { name: 'Jadoh', region: 'Meghalaya', type: 'Main Course', emoji: '🍚', description: 'Khasi rice cooked with pork or chicken in turmeric and local spices — Meghalaya\'s comfort food.', priceRange: '₹80-150', mustTry: true },
  { name: 'Siddu', region: 'Himachal Pradesh', type: 'Main Course', emoji: '🫓', description: 'Steamed wheat bread stuffed with walnuts and poppy seeds, served with ghee — a Himachali winter staple.', priceRange: '₹50-100', mustTry: false },
  { name: 'Bamboo Chicken', region: 'Andhra Pradesh', type: 'Main Course', emoji: '🍗', description: 'Chicken marinated in tribal spices and slow-cooked inside bamboo over charcoal fire — smoky and tender.', priceRange: '₹150-250', mustTry: true },
  { name: 'Chettinad Chicken', region: 'Tamil Nadu', type: 'Main Course', emoji: '🍛', description: 'Fiery chicken curry with freshly ground spices including star anise, kalpasi, and marathi mokku — intensely aromatic.', priceRange: '₹150-300', mustTry: true },
  { name: 'Kerala Sadya', region: 'Kerala', type: 'Thali', emoji: '🍌', description: 'Grand vegetarian feast of 24+ dishes served on banana leaf — the ultimate South Indian dining experience.', priceRange: '₹200-400', mustTry: true },
  { name: 'Poha Jalebi', region: 'Madhya Pradesh', type: 'Breakfast', emoji: '🍳', description: 'Flattened rice cooked with turmeric and peanuts, paired with crispy jalebis — MP\'s beloved morning ritual.', priceRange: '₹30-60', mustTry: true },
  { name: 'Bhutte ka Kees', region: 'Madhya Pradesh', type: 'Snack', emoji: '🌽', description: 'Grated corn cooked in milk with spices — Indore\'s beloved street food that\'s creamy and addictive.', priceRange: '₹40-80', mustTry: false },
  { name: 'Fish Curry Rice', region: 'Goa / Karnataka', type: 'Main Course', emoji: '🐟', description: 'Tangy coconut-based fish curry with steamed rice — the everyday coastal comfort food.', priceRange: '₹100-200', mustTry: true },
  { name: 'Misal Pav', region: 'Maharashtra', type: 'Snack', emoji: '🫘', description: 'Spicy sprouted moth bean curry topped with farsan, onion, and lemon — Maharashtra\'s fiery breakfast icon.', priceRange: '₹40-80', mustTry: true },
  { name: 'Eromba', region: 'Manipur', type: 'Main Course', emoji: '🌿', description: 'Boiled vegetables mashed with fermented fish and chillies — Manipur\'s essential everyday dish.', priceRange: '₹60-100', mustTry: false },
  { name: 'Dhokla', region: 'Gujarat', type: 'Snack', emoji: '🟡', description: 'Steamed fermented gram flour cake — spongy, tangy, and healthy. Gujarat\'s most famous export.', priceRange: '₹30-60', mustTry: true },
  { name: 'Dham', region: 'Himachal Pradesh', type: 'Thali', emoji: '🍽️', description: 'Traditional ceremonial feast cooked by Botis (hereditary cooks) in brass utensils — slow-cooked perfection.', priceRange: '₹150-250', mustTry: true },
  { name: 'Smoked Pork with Axone', region: 'Nagaland', type: 'Main Course', emoji: '🥓', description: 'Pork smoked over wood fire served with axone (fermented soybean) — Naga cuisine at its finest.', priceRange: '₹150-250', mustTry: true },
  { name: 'Appam with Stew', region: 'Kerala', type: 'Breakfast', emoji: '🥞', description: 'Lacy rice pancakes with a soft center, paired with coconut milk vegetable stew — Kerala\'s Sunday morning tradition.', priceRange: '₹60-100', mustTry: true },
  { name: 'Pyaaz Kachori', region: 'Rajasthan', type: 'Snack', emoji: '🫓', description: 'Crispy deep-fried pastry stuffed with spiced onion filling — Jodhpur\'s legendary street snack.', priceRange: '₹20-40', mustTry: true },
];

// ========================================
// CHAT RESPONSE PATTERNS
// ========================================
TT.chatPatterns = [
  {
    keywords: ['hello', 'hi', 'hey', 'namaste', 'howdy'],
    response: "Namaste! 🙏 I'm your Travel Trippy AI companion! I know India's best-kept secrets — hidden waterfalls, ancient villages, secret viewpoints, and incredible local food spots. Ask me anything! 🌏✨\n\nTry asking:\n• \"Suggest a peaceful weekend getaway near Delhi\"\n• \"Hidden waterfalls in South India\"\n• \"Best food in Rajasthan\"\n• \"Plan a 3-day budget trip from Mumbai\""
  },
  {
    keywords: ['peaceful', 'quiet', 'serene', 'calm', 'relaxing'],
    response: "For a peaceful escape, here are my top picks:\n\n🌿 **Tirthan Valley, HP** — Crystal rivers, trout fishing, zero crowds\n🏔️ **Kanatal, Uttarakhand** — Apple orchards, Himalayan solitude\n🌲 **Lepchajagat, WB** — Misty forest hamlet near Darjeeling\n🏞️ **Valparai, TN** — Misty tea plantations & wildlife\n🧘 **Ponmudi, Kerala** — Golden peak with rolling clouds\n\nWhich one catches your eye? I can tell you more! 😊"
  },
  {
    keywords: ['adventure', 'trek', 'trekking', 'hiking', 'thrill', 'adrenaline'],
    response: "Adventure awaits! Here are India's hidden adventure gems:\n\n⛰️ **Sandakphu Trek, WB** — See 4 of world's 5 highest peaks!\n🏔️ **Spiti Valley, HP** — Cold desert motorcycle paradise\n🌸 **Dzukou Valley, Nagaland** — Valley of flowers with camping\n🌊 **Gandikota, AP** — Camp at India's Grand Canyon\n🌳 **Nongriat, Meghalaya** — 3500 steps to living root bridges\n\nWhat's your adventure level — moderate or extreme? 🧗"
  },
  {
    keywords: ['budget', 'cheap', 'affordable', 'student', 'backpack'],
    response: "Budget-friendly hidden gems that won't break the bank:\n\n💰 **Under ₹3,000 (2 days):**\n• Orchha, MP — Medieval town, zero tourists\n• Gokarna, Karnataka — Beautiful beaches, beach shacks\n• Lonar, Maharashtra — Meteor crater lake!\n\n💰 **Under ₹5,000 (3 days):**\n• Mawlynnong, Meghalaya — Asia's cleanest village\n• Hampi, Karnataka — Ancient ruins + backpacker vibes\n• Chopta, Uttarakhand — Mini Switzerland trek\n\nAll include stay, food & local travel! Want a detailed plan? 🎒"
  },
  {
    keywords: ['food', 'eat', 'cuisine', 'dish', 'restaurant', 'foodie'],
    response: "Ah, a fellow foodie! India's hidden food gems:\n\n🍛 **Chettinad, TN** — Fiery Chettinad Chicken & Kavuni Arisi\n🫓 **Indore, MP** — Poha Jalebi & Bhutte ka Kees capital\n🍗 **Araku Valley, AP** — Bamboo Chicken cooked by tribals\n🥟 **Ladakh** — Momos, Thukpa & Butter Tea in monasteries\n🐟 **Gokarna, KA** — Fresh fish curry by the beach\n🍰 **Jodhpur, RJ** — Pyaaz Kachori & Makhaniya Lassi\n\nWhich region's food interests you most? 🤤"
  },
  {
    keywords: ['weekend', 'short trip', '2 days', 'quick getaway', 'nearby'],
    response: "Quick weekend getaway picks:\n\n📍 **From Delhi:** Kanatal (6hrs), Orchha (5hrs)\n📍 **From Mumbai:** Lonar Crater (6hrs), Kaas Plateau (5hrs)\n📍 **From Bangalore:** Shettihalli Church (4hrs), Hampi (6hrs)\n📍 **From Kolkata:** Lepchajagat (3hrs), Sandakphu (6hrs)\n📍 **From Chennai:** Araku Valley (8hrs), Chettinad (5hrs)\n\nTell me your starting city and I'll craft the perfect weekend plan! 🗺️"
  },
  {
    keywords: ['waterfall', 'waterfalls', 'cascade', 'falls'],
    response: "India's hidden waterfalls that'll leave you speechless:\n\n💧 **Chitrakote Falls, Chhattisgarh** — India's widest waterfall (Niagara of India)\n⛲ **Athirapally Falls, Kerala** — The Bahubali waterfall, 80ft drop\n💎 **Bhedaghat, MP** — Falls through marble canyon (moonlight boat rides!)\n🌊 **Nongriat Falls, Meghalaya** — Hidden under living root bridges\n🌿 **Ponmudi Falls, Kerala** — Through 22 hairpin bends\n\nVisit during monsoon for maximum power! Which region interests you? 🌧️"
  },
  {
    keywords: ['temple', 'spiritual', 'religious', 'meditation', 'monastery'],
    response: "Sacred & spiritual hidden gems:\n\n🕉️ **Tawang Monastery, AP** — India's largest, 400 years old\n🧘 **Phugtal Monastery, Ladakh** — Cave monastery at cliff's edge\n🛕 **Pattadakal, KA** — UNESCO Chalukyan temples\n⛪ **Shettihalli Church, KA** — Submerged Gothic church\n🏛️ **Orchha Temples, MP** — Deserted medieval temples\n💙 **Bundi, RJ** — City of stepwells & paintings\n\nSeek peace, architecture, or both? I'll guide you! 🙏"
  },
  {
    keywords: ['family', 'kids', 'children', 'safe', 'parents', 'elderly', 'senior'],
    response: "Family-friendly hidden gems with easy access:\n\n👨‍👩‍👧‍👦 **Perfect for Families:**\n• Mawlynnong, Meghalaya — Clean, safe, magical\n• Hampi, Karnataka — History + adventure, very safe\n• Orchha, MP — Peaceful, walkable, rich history\n• Athirapally, Kerala — Easy access to stunning waterfall\n• Chettinad, TN — Heritage mansions & amazing food\n\n🧓 **Senior-Friendly:**\n• Bundi, Rajasthan — Flat terrain, rich culture\n• Araku Valley, AP — Scenic train journey, gentle terrain\n• Ponmudi, Kerala — Scenic drive, minimal walking\n\nShall I plan a specific trip? 🏡"
  },
  {
    keywords: ['photography', 'photo', 'camera', 'instagram', 'picture'],
    response: "📸 Photography havens that are Instagram gold:\n\n🏔️ **Spiti Valley** — Stark landscapes, monasteries, Milky Way\n💎 **Bhedaghat** — Marble rocks moonlight reflection\n☄️ **Lonar Lake** — Pink meteor crater from drone\n⛪ **Shettihalli Church** — Submerged church at dawn\n🌺 **Kaas Plateau** — Carpet of wildflowers\n💕 **Mandu** — Floating palace between two lakes\n🌸 **Dzukou Valley** — Wildflower carpets & misty peaks\n🐆 **Jawai** — Leopards on granite boulders\n\nGolden hour, blue hour, or astro photography? I'll suggest the best spots! 📷"
  },
  {
    keywords: ['plan', 'itinerary', 'trip plan', 'schedule', 'route'],
    response: "I'd love to help plan your trip! Tell me:\n\n📍 Starting city?\n📅 How many days?\n💰 Budget range?\n❤️ Interests (adventure/food/nature/culture/photography)?\n👥 Traveling with (solo/couple/family/friends)?\n\nI'll create a day-by-day itinerary with:\n✅ Hidden gem destinations\n✅ Route & travel time\n✅ Local food recommendations\n✅ Best activities\n✅ Budget breakdown\n✅ Local insider tips\n\nJust share the details! 🗺️"
  },
  {
    keywords: ['north east', 'northeast', 'seven sisters', 'unexplored'],
    response: "North-East India — India's most magical frontier!\n\n🌿 **Mawlynnong, Meghalaya** — Asia's cleanest village\n🌳 **Nongriat, Meghalaya** — Living root bridges\n🏝️ **Majuli, Assam** — World's largest river island\n🌾 **Ziro Valley, Arunachal** — Rice paddy UNESCO heritage\n🌸 **Dzukou Valley, Nagaland** — Valley of wildflowers\n🦌 **Loktak Lake, Manipur** — Floating national park\n🕉️ **Tawang, Arunachal** — Dramatic monastery town\n🏔️ **Mechuka, Arunachal** — India's Shangri-La\n\nNorth-East requires Inner Line Permits for some states. Want help planning? 🗺️"
  },
  {
    keywords: ['monsoon', 'rain', 'rainy', 'july', 'august', 'september'],
    response: "Monsoon magic — India's most beautiful season to travel!\n\n🌺 **Kaas Plateau, MH** — 850 species of wildflowers bloom\n💧 **Chitrakote Falls, CG** — Widest waterfall at full power\n⛪ **Shettihalli Church, KA** — Church submerged in monsoon waters\n🌸 **Dzukou Valley, Nagaland** — Wildflower carpets\n🌊 **Athirapally, Kerala** — 130ft wide thundering falls\n💕 **Mandu, MP** — Floating palaces when lakes fill up\n\n☔ Pro tips: Carry rain gear, roads can be tricky, but the beauty is unmatched! 🌈"
  },
  {
    keywords: ['winter', 'snow', 'december', 'january', 'cold'],
    response: "Winter wonderland destinations:\n\n❄️ **Chopta, Uttarakhand** — Snow-covered Mini Switzerland\n🏔️ **Kalpa, HP** — Kinner Kailash views in crystal air\n🐪 **Nubra Valley, Ladakh** — Cold desert dunes (summer only though!)\n🐆 **Jawai, Rajasthan** — Best leopard sighting season\n🌫️ **Lambasingi, AP** — South India's coldest spot\n💙 **Bundi, Rajasthan** — Pleasant weather, perfect for walking\n\nWinter is peak season for most hidden gems. Plan 2 weeks ahead! 🧣"
  },
];

// ========================================
// AGE GROUP METADATA
// ========================================
TT.ageGroups = {
  'students': {
    label: 'Students (18-25)',
    icon: '🎓',
    traits: ['Budget-friendly', 'Adventure', 'Photography', 'Backpacking'],
    budgetRange: '₹2,000 - ₹5,000'
  },
  'young-professionals': {
    label: 'Young Professionals (25-40)',
    icon: '💼',
    traits: ['Weekend Getaways', 'Road Trips', 'Experiences', 'Nature'],
    budgetRange: '₹5,000 - ₹15,000'
  },
  'families': {
    label: 'Families (30-60)',
    icon: '👨‍👩‍👧‍👦',
    traits: ['Safe', 'Comfortable', 'Family-friendly', 'Cultural'],
    budgetRange: '₹8,000 - ₹20,000'
  },
  'seniors': {
    label: 'Senior Citizens (60+)',
    icon: '🧓',
    traits: ['Peaceful', 'Spiritual', 'Easy Access', 'Cultural'],
    budgetRange: '₹5,000 - ₹15,000'
  }
};

// ========================================
// INDIAN STATES for Filters
// ========================================
TT.states = [
  'All States', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Chhattisgarh',
  'Gujarat', 'Himachal Pradesh', 'Karnataka', 'Kerala', 'Ladakh',
  'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Nagaland',
  'Rajasthan', 'Tamil Nadu', 'Uttarakhand', 'West Bengal'
];

// ========================================
// INTERESTS for Profile
// ========================================
TT.interests = [
  { id: 'adventure', label: 'Adventure', icon: '🧗' },
  { id: 'food', label: 'Food & Cuisine', icon: '🍛' },
  { id: 'nature', label: 'Nature', icon: '🌿' },
  { id: 'spiritual', label: 'Spiritual', icon: '🕉️' },
  { id: 'luxury', label: 'Luxury', icon: '✨' },
  { id: 'photography', label: 'Photography', icon: '📸' },
  { id: 'wildlife', label: 'Wildlife', icon: '🦁' },
  { id: 'history', label: 'History', icon: '📜' },
  { id: 'culture', label: 'Culture', icon: '🎭' },
  { id: 'beaches', label: 'Beaches', icon: '🏖️' },
];

// ========================================
// GALLERY DATA
// ========================================
TT.galleryCategories = [
  { id: 'all', label: 'All' },
  { id: 'mountains', label: 'Mountains' },
  { id: 'lakes', label: 'Lakes' },
  { id: 'beaches', label: 'Beaches' },
  { id: 'forests', label: 'Forests' },
  { id: 'villages', label: 'Villages' },
  { id: 'heritage', label: 'Heritage' },
  { id: 'waterfalls', label: 'Waterfalls' },
];

// ========================================
// SAMPLE REVIEWS
// ========================================
TT.sampleReviews = [
  { author: 'Priya S.', date: 'Nov 2025', rating: 5, text: 'Absolutely magical! The mist, the silence, the untouched beauty — this is the India I was searching for. Local guides were so warm and helpful.', destId: 'mawlynnong' },
  { author: 'Rahul M.', date: 'Oct 2025', rating: 5, text: 'Spiti changed my perspective on travel. The raw beauty and the kindness of people here is unmatched. Go before it gets crowded!', destId: 'spiti-valley' },
  { author: 'Ananya K.', date: 'Sep 2025', rating: 4, text: 'The canyon view at sunset was breathtaking. Camping under the stars was incredible. Just carry enough water and food supplies.', destId: 'gandikota' },
  { author: 'Vikram R.', date: 'Dec 2025', rating: 5, text: 'Orchha is what Rajasthan used to be 30 years ago — grand, beautiful, and blissfully empty. The palace paintings are incredible.', destId: 'orchha' },
  { author: 'Meera J.', date: 'Aug 2025', rating: 5, text: 'Seeing the flower carpet at Kaas was surreal. Felt like walking on a painting. Book early — daily entry is limited!', destId: 'kaas-plateau' },
  { author: 'Arjun D.', date: 'Jan 2026', rating: 5, text: 'The leopard safari at Jawai was incredible. Saw 3 leopards on granite boulders at sunrise. The Rabari guides are phenomenal.', destId: 'jawai' },
];
